using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SV
{
    internal class Class_Controle
    {
        // NIVEL DE ACESSO
        // DEVELOPER
        // NESTA OPÇÃO O USUÁRIO TERÁ ACESSO A TODOS OS RECURSOS DO SISTEMA SEM RESTRIÇÕES

        // ADMINISTRADOR
        // NESTA OPÇÃO O USUÁRIO TERÁ ACESSO A TODOS OS RECURSOS DO SISTEMA

        // COMPRAS
        // NESTA OPÇÃO O USUÁRIO TERÁ ACESSO A TODOS OS RECURSOS DE COMPRAS

        // CONSULTA
        // NESTA OPÇÃO O USUÁRIO TERÁ ACESSO APENAS A CONSULTA DE PRODUTOS

        // FISCAL
        // NESTA OPÇÃO O USUÁRIO TERÁ ACESSO A TODOS OS RECURSOS RELACIONADOS APENAS A CONSULTA E ATRIBUIÇÕES BASICAS DO SISTEMA

        // GERENTE
        // NESTA OPÇÃO O USUÁRIO TERÁ ACESSO A TODOS OS RECURSOS RELACIONADOS AO GERENCIAMENTO DA LOJA
       
        // RH
        // NESTA OPÇÃO O USUÁRIO TERÁ ACESSO A TODOS OS RECURSOS RELACIONADOS AO DEPARTAMENTO PESSOAL

        // SUPERVISOR
        // NESTA OPÇÃO O USUÁRIO TERÁ ACESSO A TODOS OS RECURSOS RELACIONADOS AO SUPERVISOR DA LOJA
    }
}
